<div class="hero-unit">
    <p>Numero de Pedido:<?php echo $this->paramsOrder['order'];?></p>
    <p>Fecha:<?php echo $this->paramsOrder['date'];?></p>
    <p>Nombre:<?php echo $this->paramsOrder['usename'];?></p>
          <div class="bs-docs-example">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Imagen</th>
                  <th>Art&iacute;culo</th>
                  <th>C&oacute;digo</th>
                  <th>Puntos</th>
                  <th>Cantidad</th>
                </tr>
              </thead>
              <tbody>
<?php foreach ($this->paramsOrder['allCart'] as $item) :?>                  
             <tr>
              <td><img src="<?php echo $this->basePath('img/product/'.$item['thumb_image']); ?>"></td>
              <td><?php echo $item['other_sku'];?></td>
              <td><?php echo $item['sku'];?></td>
              <td><?php echo number_format(((float)$item['price']), 0, '.', ',');?></td>
              <td><?php echo $item['quantity'];?></td>
             </tr>  
<?php endforeach;?>             
              </tbody>
            </table>
           </div>   

</div>
    <a class="btn btn-success btn-large" href="<?php echo $this->basePath('user/logout'); ?>">Terminar</a> 
    <a class="btn btn-info btn-large" href="#" onclick="javascript:window.print();">Imprimir</a>  