<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Creditshistory implements CreditshistoryInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var int              
     */
      protected $idperiod;  

    /**
     * @var int              
     */
      protected $idusername;  

    /**
     * @var int              
     */
      protected $credits;  

    /**
     * @var int              
     */
      protected $payments;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set idperiod
     *
     * @param int $idperiod
     * @return type                   
     */            
	public function setIdperiod($idperiod){
		$this->idperiod = (int) $idperiod;
	}
    /**
     * Get idperiod
     *
     * @return int
     */          
	public function getIdperiod(){
		return $this->idperiod;
	}
    /**
     * Set idusername
     *
     * @param int $idusername
     * @return type                   
     */            
	public function setIdusername($idusername){
		$this->idusername = (int) $idusername;
	}
    /**
     * Get idusername
     *
     * @return int
     */          
	public function getIdusername(){
		return $this->idusername;
	}
    /**
     * Set credits
     *
     * @param int $credits
     * @return type                   
     */            
	public function setCredits($credits){
		$this->credits = (int) $credits;
	}
    /**
     * Get credits
     *
     * @return int
     */          
	public function getCredits(){
		return $this->credits;
	}
    /**
     * Set payments
     *
     * @param int $payments
     * @return type                   
     */            
	public function setPayments($payments){
		$this->payments = (int) $payments;
	}
    /**
     * Get payments
     *
     * @return int
     */          
	public function getPayments(){
		return $this->payments;
	}
}

?>