<div class="hero-unit">

          <div class="bs-docs-example">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Imagen</th>
                  <th>Art&iacute;culo</th>
                  <th>C&oacute;digo</th>
                  <th>Puntos</th>
                  <th>Cantidad</th>
                  <th>Accion</th>
                  <th>Sub Total</th>
                </tr>
              </thead>
              <tbody>
<?php $total=0; ?> 
<?php foreach($this->allcart as $row) : ?>                   
                <tr>
                  <td><img src="<?php echo $this->basePath('img/product/'.$row['thumb_image']); ?>" /></td>
                  <td><?php echo $row['other_sku']; ?></td>
                  <td><?php echo $row['sku']; ?></td>
                  <td><?php echo number_format($row['price'], 0, '.', ','); ?></td>
                  <td><?php echo $row['quantity']; ?></td>
                  <td>
                      <form action="<?php echo $this->basePath('carrito/1'); ?>" 
                          method="POST" name="delete" style="display: inline;">
                        <button type="submit" class="btn">Eliminar</button>
                        <input type="hidden" name="user_id" value="<?php echo $row['user_id']; ?>" />
                        <input type="hidden" name="product_id" value="<?php echo $row['product_id']; ?>" />
                    </form>
                  </td>
                  <td><?php echo number_format($row['line_total'], 0, '.', ','); ?></td>
                </tr>
<?php $total +=$row['line_total']; ?> 
<?php endforeach; ?>
             <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>Total</td>
              <td><?php echo number_format($total, 0, '.', ','); ?></td>                
             </tr>    
              </tbody>
            </table>
          </div>
    <a class="btn btn-success btn-large" href="<?php echo $this->basePath('checkout'); ?>">Checkout</a>    
</div>
