<?php $row = $this->producto;?>
<div class="hero-unit">
    <h3><span class="zf-green"><?php echo $row['other_sku'];?></span></h3>
    <p>
    <ul class="thumbnails">
    <li class="span2">
    <div class="thumbnail">
        <a href="<?php echo $this->basePath('img/product/'.$row['full_image']); ?>" 
           title="<?php echo $row['other_sku'];?>" 
           rel="lightbox[product504]">
        <img src="<?php echo $this->basePath('img/product/'.$row['full_image']); ?>" 
             data-src="holder.js/260x180"  
             alt="<?php echo $row['other_sku'];?>" ></a></div>
        </li>
        </ul>
    </p>
    <p><?php echo $row['description'];?></p>
    <p><?php echo $row['price'].' '.$row['currency'];?></p>
    <p>
    <form action="<?php echo $this->basePath('carrito/2'); ?>" method="post"  class="addtocart_form" >
    <label for="quantity504" class="quantity_box">Cantidad:&nbsp;</label><input type="text" class="inputboxquantity" size="4" id="quantity504" name="quantity[]" value="1" />
    <input type="button" class="quantity_box_button quantity_box_button_up" value="+" onclick="var qty_el = document.getElementById('quantity504'); var qty = qty_el.value; if( !isNaN( qty )) qty_el.value++;return false;" />
    <input type="button" class="quantity_box_button quantity_box_button_down"  value="-" onclick="var qty_el = document.getElementById('quantity504'); var qty = qty_el.value; if( !isNaN( qty ) && qty > 0 ) qty_el.value--;return false;" />
    <input type="hidden" name="product_id" value="<?php echo $row['id'];?>"/>
    <input type="hidden" name="user_id" value="1"/>
    <input type="hidden" name="quantity" value="1"/>
    <input type="hidden" name="price" value="<?php echo $row['price'];?>"/>
    <input type="hidden" name="line_total" value="<?php echo $row['price'];?>"/>
    <button type="submit" class="btn">Pedido</button>   
    </form> 
    </p>
</div>